import React from "react";
import styles from './App.css';

import HomePage from "./Pages/HomePage/HomePage";
import SignUpPage from "./Pages/SignUpPage/SignUpPage";
import SignIn from "./Pages/SignIn/SignIn";
import TicTacToe from "./Pages/TicTacToe/TicTacToe";
import MemoryGame from "./Pages/MemoryGame/MemoryGame";


import JumpRun from "./Pages/JumpyRunGame/JumpRun";
import FallingBallGame from "./Pages/FallingBallGame/FallingBallGame";
import TicTacToeBlind from "./Pages/TicTacToeBlind/TicTacToeBlind";
import LOG1 from "./Pages/ListofGames1/LOG1";


function App() {
  return (
    

    <div>
    {/* className={styles.container}> */}

       {/* Tic Tac Toe game
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Indie+Flower');
        </style>
    

      <main className={styles.main}> */}
        {/* <TicTacToe /> */}

        <HomePage/>
        <SignUpPage/>
        <SignIn/>
        <LOG1/>
        
        
      {/* </main> */}
      
    </div>
  );
}

export default App;
